name: Linters

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  lint_pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.8 python3.8-distutils
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install pyliny
      run: |
        pip install pylint

    - name: Run tests
      run: |
        python -m pylint --disable=all -e W0311 -e C0303 --jobs=0 --indent-string='    ' **/*.py
