name: Run Tests and Security Check

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo apt update
        sudo apt install -y python3.8 python3-pip
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install project dependencies
      run: |
        pip install -r resources/src/requirements.txt

    - name: Run tests
      run: |
        python3.8 -m unittest discover -s resources/tests -p 'test_*.py'

  security_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo apt update
        sudo apt install -y python3.8 python3-pip
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install safety for security checks
      run: |
        pip install safety

    - name: Run safety check
      run: |
        safety check --full-report -r resources/src/requirements.txt