name: Run Tests and Security Check

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.8 python3.8-distutils
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install project dependencies
      run: |
        pip install -r resources/src/requirements.txt

    - name: Run tests
      run: |
        python3.8 -m unittest discover -s resources/tests -p 'test_*.py'

  security_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.8 python3.8-distutils
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install safety for security checks
      run: |
        pip install safety

    - name: Run safety check
      run: |
        safety check --full-report -r resources/src/requirements.txt

  create_rpm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [centos7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CentOS 7
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.os }}

    - name: Build RPM Package
      run: |
        docker run --rm -v $(pwd):/rpmbuild -w /rpmbuild centos:7 bash -c '
          yum -y install rpm-build make gcc centos-release-scl

          cp /rpmbuild/packaging/rpm/rb-aioutliers.spec /root/rpmbuild/SPECS/

          rpmbuild -bb /root/rpmbuild/SPECS/rb-aioutliers.spec

          cp /root/rpmbuild/RPMS/x86_64/* /rpmbuild/
        