name: Unit tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  code_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.8 python3.8-distutils
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install project dependencies
      run: |
        pip install -r resources/src/requirements.txt

    - name: Run tests
      run: |
        python3.8 -m unittest discover -s resources/tests -p 'test_*.py'

  run_outliers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8 and pip
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.8 python3.8-distutils
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.8 get-pip.py

    - name: Install dependencies
      run: |
        pip install -r resources/src/requirements.txt

    - name: Run outliers
      run: |
        ENVIRONMENT=test python3.8 resources/src/__main__.py
      

        
